### ISSUE TITLE
timerElapsedTimeDidChange not working when app in background or Lock screen. 

### ISSUE THREAD

**Issue by nothanks1** [MagicTimerFW/MagicTimer#19]
Hello. Everything fine while app running. But when it on background or locked screen, the "timerElapsedTimeDidChange" not changing. What should i do to catch TimeDidChange? 

"timer.isActiveInBackground = true" is enable.

PS: Thank you for your project, very useful.

**Comment by sadeghgoo** [comment]
Hi @nothanks1 
Well, actually when you're in background mode none of the callbacks of the MagicTimer works. And this property is just for calculating time you've been in background.

**Comment by nothanks1** [comment]
I need this feature: Send push notification when timer is 60 sec. 

Ok, seems like i should just add delay in my local notification center. i thought i could made it with "timerElapsedTimeDidChange". Thank you for fast response!
